name: Boundary Condition Generation

on:
  push:
  workflow_dispatch:

jobs:
  generate-boundary-conditions:
    runs-on: ubuntu-latest
    steps:

      # ✅ 1️⃣ Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ 2️⃣ Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ 3️⃣ Verify `.obj` File Exists in `data/`
      - name: Check `simulation_mesh.obj`
        run: ls -l ./data/testing-input-output/

      # ✅ 4️⃣ Run Boundary Conditions Script FIRST from `src/`
      - name: Generate Boundary Conditions
        run: python src/boundary_conditions.py ./data/testing-input-output/simulation_mesh.obj

      # ✅ 5️⃣ Validate `boundary_conditions.json` Formatting
      - name: Check JSON Formatting
        run: |
          python -c "import json; f = open('data/testing-input-output/boundary_conditions.json'); json.load(f); f.close()"
          echo "✅ JSON formatting is valid."

      # ✅ 6️⃣ Run Unit & Integration Tests AFTER Boundary Conditions Generation
      - name: Run unit tests  
        run: pytest tests/test_unit_validation.py --verbose  

      - name: Run integration tests  
        run: pytest tests/test_integration_validation.py --verbose

      # ✅ 7️⃣ Commit and Push Updated JSON File (Only If Tests Passed)
      - name: Commit and Push Boundary Conditions JSON
        if: success()
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

          # Check if there are changes to commit
          if git diff --quiet && git diff --staged --quiet; then
            echo "ℹ️ No changes to commit. Skipping push."
          else
            git add data/testing-input-output/boundary_conditions.json
            git commit -m "Auto-update: Passed tests and updated boundary conditions JSON file"
            git push origin HEAD
          fi



