name: Boundary Condition Generation

on:
  push:
  workflow_dispatch:

jobs:
  generate-boundary-conditions:
    runs-on: ubuntu-latest
    steps:

      # ✅ 1️⃣ Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # ✅ 3️⃣ Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ 4️⃣ Grant Execution Permissions for Dropbox Shell Script (Download)
      - name: Make `download_from_dropbox.sh` Executable
        run: chmod +x src/download_from_dropbox.sh

      # ✅ 5️⃣ Run Dropbox Shell Script to Fetch Files
      - name: Download Simulation Files from Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: src/download_from_dropbox.sh

      # ✅ 6️⃣ Verify Downloaded Files Exist (Programmatic Check)
      - name: Verify File Existence
        run: |
          if [ -f $GITHUB_WORKSPACE/downloaded_simulation_files/simulation_mesh.json ] && [ -f $GITHUB_WORKSPACE/downloaded_simulation_files/initial_data.json ]; then
            echo "✅ Both simulation_mesh.json and initial_data.json were downloaded successfully."
          else
            echo "❌ ERROR: One or both of the required files were not found!"
            exit 1
          fi

      # ✅ 7️⃣ Delete Previous `fluid_simulation_input.json` If Exists
      - name: Delete Previous Fluid Simulation Input JSON
        run: |
          if [ -f $GITHUB_WORKSPACE/downloaded_simulation_files/fluid_simulation_input.json ]; then
            rm $GITHUB_WORKSPACE/downloaded_simulation_files/fluid_simulation_input.json
            echo "🗑️ Deleted previous fluid_simulation_input.json file."
          else
            echo "ℹ️ No previous fluid_simulation_input.json found—proceeding with new generation."
          fi

      # ✅ 8️⃣ Run JSON Merge Script
      - name: Merge JSON Files
        working-directory: ./src
        run: python merge_json_files.py $GITHUB_WORKSPACE/downloaded_simulation_files/simulation_mesh.json $GITHUB_WORKSPACE/downloaded_simulation_files/initial_data.json $GITHUB_WORKSPACE/downloaded_simulation_files/fluid_simulation_input.json

      # ✅ Debug: List Directory Before Verifying Output Files
      - name: Debug Directory Structure Before Verification
        run: ls -R $GITHUB_WORKSPACE

      # ✅ 9️⃣ Debug Generated Files (Verify Output File Exists)
      - name: Debug Generated Files
        run: ls -l $GITHUB_WORKSPACE/downloaded_simulation_files/

      # ✅ 🔟 Run Unit and Integration Tests (Commented Out)
      # - name: Run Tests
      #   run: |
      #     python -m unittest discover -s tests -p "*.py"

      # ✅ 1️⃣1️⃣ Grant Execution Permissions for Dropbox Shell Script (Upload)
      - name: Make `upload_to_dropbox.sh` Executable
        run: chmod +x src/upload_to_dropbox.sh

      # ✅ 🔍 Debugging Step BEFORE Uploading to Dropbox
      - name: Debug Before Dropbox Upload
        run: |
          echo "🔍 Checking directory structure before upload..."
          ls -R $GITHUB_WORKSPACE

      # ✅ 1️⃣2️⃣ Upload Generated Output File to Dropbox
      - name: Upload Fluid Simulation Input to Dropbox
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: src/upload_to_dropbox.sh
