name: OpenFOAM Simulation
on:
  push:
    branches:
      - main

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OpenFOAM
        run: |
          sudo apt update
          sudo apt install -y openfoam
          source /opt/openfoam*/etc/bashrc

      - name: Run CFD Simulation
        run: |
          cd simulation_folder
          openfoam_command_here

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results/*
          git commit -m "Simulation results"
          git push origin main



