name: OpenFOAM Simulation
on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  install-openfoam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common wget

      - name: Add OpenFOAM Repository & Install OpenFOAM
        run: |
          sudo wget -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
          sudo apt update
          sudo apt install -y openfoam2306  # Ensure this matches the latest available version

      - name: Set Up OpenFOAM Environment
        run: |
          echo "source /opt/openfoam2306/etc/bashrc" >> ~/.bashrc
          source /opt/openfoam2306/etc/bashrc
          echo "OpenFOAM environment sourced!"

      - name: Verify OpenFOAM Installation
        run: |
          source /opt/openfoam2306/etc/bashrc
          foamVersion  # Alternative verification command
          echo "OpenFOAM installation verified!"



