name: Boundary Condition Generation  # Workflow name

on:
  push:  # ✅ Runs on every commit to any branch
  workflow_dispatch:  # ✅ Allows manual triggering too

jobs:
  generate-boundary-conditions:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Step: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Step: Verify `.obj` File Exists in `testing-input-output/`
      - name: Check if `testing-Body.obj` is present
        run: |
          ls -l ./testing-input-output/

      # 3️⃣ Step: Run Python Script to Create `boundary_conditions.json`
      # ✅ Passes `testing-Body.obj` as an argument to `boundary_conditions.py`
      - name: Generate Boundary Conditions from `testing-Body.obj`
        run: |
          python boundary_conditions.py ./testing-input-output/testing-Body.obj

      # Debugging: Verify `boundary_conditions.json` File Creation
      - name: Verify `boundary_conditions.json` File Creation
        run: |
          ls -l ./testing-input-output/
