name: OpenFOAM Docker Simulation
on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  run-openfoam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fix Package Conflicts
        run: |
          sudo apt-get remove -y containerd containerd.io || echo "No containerd packages found."
          sudo apt-get autoremove -y
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          echo "Docker installed and running!"

      - name: Pull OpenFOAM Docker Image
        run: |
          docker pull opencfd/openfoam-run:2306
          echo "OpenFOAM Docker image pulled successfully!"

      - name: Run OpenFOAM Simulation in Docker
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace opencfd/openfoam-run:2306 blockMesh -help
          echo "OpenFOAM command executed inside Docker!"



