name: OpenFOAM Simulation
on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y universe
          sudo apt update

      - name: Install OpenFOAM (Official Method)
        run: |
          sudo apt install -y openfoam2306  # Replace with the latest version available
          echo "source /usr/lib/openfoam/openfoam2306/etc/bashrc" >> ~/.bashrc
          source ~/.bashrc

      - name: Verify OpenFOAM Installation
        run: |
          foamSystemCheck  # Checks if OpenFOAM is correctly installed
          echo "OpenFOAM installation verified!"

      - name: Run CFD Simulation
        run: |
          cd simulation_folder
          blockMesh  # Example OpenFOAM command, replace with actual simulation steps
          openfoam_command_here

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results/*
          git commit -m "Simulation results"
          git push




