name: OpenFOAM Dropbox Automation

on:
  push:
    branches:
      - '**'
  workflow_dispatch:  # This allows manual execution from GitHub Actions UI

jobs:
  run-openfoam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fix Package Conflicts
        run: |
          sudo apt-get remove -y containerd containerd.io || echo "No containerd packages found."
          sudo apt-get autoremove -y
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          echo "Docker installed and running!"

      - name: Pull OpenFOAM Docker Image
        run: |
          docker pull opencfd/openfoam-run:2306
          echo "OpenFOAM Docker image pulled successfully!"

      - name: Install Python Dependencies
        run: |
          pip install dropbox  # Ensure Dropbox module is installed

      - name: Run OpenFOAM Processing Script
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python openfoam_process.py
          echo "OpenFOAM processing completed!"



