name: Boundary Condition Generation

on:
  push:
  workflow_dispatch:

jobs:
  generate-boundary-conditions:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Install Dependencies (Fix Missing `pyvista`)
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyvista numpy meshio

      # 3️⃣ Verify `.obj` File Exists
      - name: Check `testing-Body.obj`
        run: ls -l ./testing-input-output/

      # 4️⃣ Run Boundary Conditions Script
      - name: Generate Boundary Conditions
        run: python boundary_conditions.py ./testing-input-output/testing-Body.obj

      # 5️⃣ Verify `boundary_conditions.json` Creation
      - name: Check Output
        run: ls -l ./testing-input-output/


