name: OpenFOAM Simulation
on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  install-openfoam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common wget

      - name: Add OpenFOAM Repository & Install OpenFOAM
        run: |
          sudo wget -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
          sudo apt update
          sudo apt install -y openfoam2306  # Ensure this matches the latest available version

      - name: Set Up OpenFOAM Environment
        run: |
          # Find the actual OpenFOAM installation directory
          OPENFOAM_DIR=$(ls -d /opt/openfoam* 2>/dev/null | tail -n 1)
          
          if [ -n "$OPENFOAM_DIR" ]; then
            echo "source $OPENFOAM_DIR/etc/bashrc" >> ~/.bashrc
            source $OPENFOAM_DIR/etc/bashrc
            echo "OpenFOAM environment sourced from $OPENFOAM_DIR!"
          else
            echo "Error: OpenFOAM installation directory not found!"
            exit 1
          fi

      - name: Verify OpenFOAM Installation
        run: |
          source ~/.bashrc
          foamVersion  # Alternative verification command
          echo "OpenFOAM installation verified!"



