name: OpenFOAM Simulation
on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  install-openfoam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common wget

      - name: Add OpenFOAM Repository & Install OpenFOAM
        run: |
          sudo wget -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
          sudo apt update
          sudo apt install -y openfoam2306

      - name: Verify OpenFOAM Installation
        run: |
          dpkg -l | grep openfoam || (echo "Error: OpenFOAM installation failed!" && exit 1)

      - name: Set OpenFOAM Environment
        run: |
          export OPENFOAM_PATH="/usr/lib/openfoam/openfoam2306"
          export PATH="$OPENFOAM_PATH/bin:$OPENFOAM_PATH/wmake:$PATH"
          export FOAM_INST_DIR="/usr/lib/openfoam"
          export WM_PROJECT_DIR="$OPENFOAM_PATH"
          export WM_THIRD_PARTY_DIR="$OPENFOAM_PATH/ThirdParty"

          echo "source $OPENFOAM_PATH/etc/bashrc" >> ~/.bashrc
          . $OPENFOAM_PATH/etc/bashrc || (echo "Error: OpenFOAM environment sourcing failed!" && exit 1)
          echo "OpenFOAM environment set successfully!"

      - name: Verify OpenFOAM Setup
        run: |
          . ~/.bashrc
          echo "Checking OpenFOAM version..."
          foamVersion || (echo "Error: OpenFOAM verification failed!" && exit 1)
          echo "OpenFOAM installation verified!"
