name: OpenFOAM Simulation
on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install OpenFOAM
        run: |
          sudo apt update
          sudo apt install -y openfoam

      - name: Set Up OpenFOAM Environment
        run: |
          if [ -f "/usr/lib/openfoam/openfoam*/etc/bashrc" ]; then
            source /usr/lib/openfoam/openfoam*/etc/bashrc
          elif [ -f "/opt/openfoam*/etc/bashrc" ]; then
            source /opt/openfoam*/etc/bashrc
          else
            echo "Error: OpenFOAM installation not found!"
            exit 1
          fi

      - name: Run CFD Simulation
        run: |
          cd simulation_folder
          openfoam_command_here

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results/*
          git commit -m "Simulation results"
          git push
