name: Configure OpenMPI for OpenFOAM

on:
  push:
    branches:
      - master
      - main

jobs:
  configure-openmpi:
    name: Use Direct OpenMPI Paths for OpenFOAM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Enable Universe Repository
      run: |
        sudo apt-add-repository universe
        sudo apt update

    - name: Install OpenMPI
      run: |
        sudo apt install -y openmpi-bin libopenmpi-dev

    - name: Export OpenMPI Paths
      run: |
        echo "export WM_MPLIB=SYSTEMOPENMPI" >> $HOME/.bashrc
        echo "export MPI_ROOT=/usr" >> $HOME/.bashrc
        echo "export MPI_ARCH_FLAGS=\"-DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX\"" >> $HOME/.bashrc
        echo "export MPI_ARCH_INC=\"-I/usr/include/openmpi\"" >> $HOME/.bashrc
        echo "export MPI_ARCH_LIBS=\"-L/usr/lib/openmpi -lmpi\"" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Verify OpenMPI Installation
      run: |
        /usr/bin/mpicc.openmpi --version
        /usr/bin/mpiexec.openmpi --version
