name: Install OpenFOAM (Modern GPG Key Handling)

on:
  push:
    branches:
      - master
      - main

jobs:
  setup-openfoam:
    name: Setup OpenFOAM with Manual Repository
    runs-on: ubuntu-latest  # Can be changed to 'debian-latest' as needed.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Prerequisites
      run: |
        # Install necessary tools
        sudo apt-get update
        sudo apt-get install -y curl wget gnupg ca-certificates software-properties-common

    - name: Add OpenFOAM Repository and GPG Key
      run: |
        # Manually add GPG key to /etc/apt/trusted.gpg.d
        wget -qO - https://dl.openfoam.com/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/openfoam.gpg > /dev/null
        
        # Add the repository manually
        echo "deb http://dl.openfoam.com/repos/deb focal main" | sudo tee /etc/apt/sources.list.d/openfoam.list

        # Update repositories
        sudo apt-get update

    - name: Install OpenFOAM
      run: |
        # Install OpenFOAM (example: version 2412)
        sudo apt-get install -y openfoam2412-default

    - name: Verify OpenFOAM Installation
      run: |
        # Ensure binaries and configuration files exist
        ls /usr/bin | grep openfoam || echo "OpenFOAM binaries not found!"
        ls /usr/share/openfoam || echo "OpenFOAM configuration directory missing!"

    - name: Configure OpenFOAM Environment
      run: |
        # Manually configure OpenFOAM environment
        echo "export WM_PROJECT_DIR=/usr/share/openfoam" >> ~/.bashrc
        echo "export PATH=/usr/bin:\$PATH" >> ~/.bashrc
        echo "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Test OpenFOAM Commands
      run: |
        # Test OpenFOAM commands
        source ~/.bashrc
        openfoam2412 || echo "OpenFOAM session failed!"
        blockMesh -help || echo "blockMesh command not found!"
