name: Run Ubuntu with X11

on: [push]

jobs:
  ubuntu-x11:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: Update and Install Dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          xvfb \
          xauth \
          fluxbox \
          gnome-terminal \
          chromium-browser \
          selenium \
          openfoam

    - name: Set up Xvfb
      run: |
        Xvfb :99 -screen 0 1280x1024x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Create .Xauthority
      run: |
        touch ~/.Xauthority
        xauth generate :99 . trusted
        chmod 600 ~/.Xauthority

    - name: Start Fluxbox (Optional - for visual confirmation)
      run: |
        fluxbox &

    - name: Run Your Applications
      run: |
        echo "Starting your applications..."
        # Example commands:
        # gnome-terminal &
        # chromium-browser --no-sandbox &
        # runOpenFOAMSimulation  # Replace with your actual OpenFOAM command

    - name: Print Xvfb Display
      run: |
        echo "Xvfb Display is: $DISPLAY"
