name: Install OpenFOAM (Manual Repository Setup)

on:
  push:
    branches:
      - master
      - main

jobs:
  setup-openfoam:
    name: Setup OpenFOAM with Manual Repository
    runs-on: ubuntu-latest  # You can change this to 'debian-latest' to test on Debian.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Prerequisites
      run: |
        # Install necessary tools
        sudo apt-get update
        sudo apt-get install -y curl wget software-properties-common ca-certificates

    - name: Add OpenFOAM Repository Manually
      run: |
        # Add the signing key
        wget -qO - https://dl.openfoam.com/pubkey.gpg | sudo apt-key add -
        
        # Add the repository manually for Ubuntu (focal in this example)
        sudo sh -c "echo 'deb http://dl.openfoam.com/repos/deb focal main' > /etc/apt/sources.list.d/openfoam.list"

        # Update repositories
        sudo apt-get update

    - name: Install OpenFOAM
      run: |
        # Install OpenFOAM package (example: version 2412)
        sudo apt-get install -y openfoam2412-default

    - name: Verify Installation
      run: |
        # Ensure binaries and configuration files exist
        ls /usr/bin | grep openfoam || echo "OpenFOAM binaries not found!"
        ls /usr/share/openfoam || echo "OpenFOAM configuration directory missing!"

    - name: Configure OpenFOAM Environment
      run: |
        # Set up environment variables manually
        echo "export WM_PROJECT_DIR=/usr/share/openfoam" >> ~/.bashrc
        echo "export PATH=/usr/bin:\$PATH" >> ~/.bashrc
        echo "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Test OpenFOAM Commands
      run: |
        # Test OpenFOAM commands
        openfoam2412 || echo "OpenFOAM session failed!"
        blockMesh -help || echo "blockMesh command not found!"
