name: Install and Configure OpenFOAM v12

on:
  push:
    branches:
      - master
      - main

jobs:
  setup-openfoam:
    name: Setup OpenFOAM v12
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Enable Universe Repository
      run: |
        sudo apt-add-repository universe
        sudo apt update

    - name: Install OpenFOAM Repository and Public Key
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu

    - name: Update Package List
      run: |
        sudo apt update

    - name: Install OpenFOAM v12
      run: |
        sudo apt -y install openfoam12

    - name: Verify OpenFOAM Installation
      run: |
        dpkg -l | grep openfoam12
        ls /opt/openfoam12/bin

    - name: Manually Set OpenFOAM Environment Variables
      run: |
        echo "export WM_PROJECT_DIR=/opt/openfoam12" >> ~/.bashrc
        echo "export FOAM_INST_DIR=/opt" >> ~/.bashrc
        echo "export PATH=/opt/openfoam12/bin:\$PATH" >> ~/.bashrc
        echo "export LD_LIBRARY_PATH=/opt/openfoam12/lib:\$LD_LIBRARY_PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Test OpenFOAM Execution
      run: |
        blockMesh -help || echo "blockMesh command not found!"
        foamExec -help || echo "foamExec command not found!"
