name: Install and Configure OpenFOAM v12 with OpenMPI

on:
  push:
    branches:
      - master
      - main

jobs:
  setup-openfoam:
    name: Setup OpenFOAM v12 and OpenMPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Enable Universe Repository
      run: |
        sudo apt-add-repository universe
        sudo apt update

    - name: Install OpenFOAM Repository and Public Key
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu

    - name: Update Package List
      run: |
        sudo apt update

    - name: Install OpenFOAM v12
      run: |
        sudo apt -y install openfoam12

    - name: Install OpenMPI
      run: |
        sudo apt install -y openmpi-bin libopenmpi-dev

    - name: Export OpenMPI Paths
      run: |
        echo "export WM_MPLIB=SYSTEMOPENMPI" >> $HOME/.bashrc
        echo "export MPI_ROOT=/usr" >> $HOME/.bashrc
        echo "export MPI_ARCH_FLAGS=\"-DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX\"" >> $HOME/.bashrc
        echo "export MPI_ARCH_INC=\"-I/usr/include/openmpi\"" >> $HOME/.bashrc
        echo "export MPI_ARCH_LIBS=\"-L/usr/lib/openmpi -lmpi\"" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Configure OpenFOAM Environment
      run: |
        echo ". /opt/openfoam12/etc/bashrc" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Verify OpenFOAM Installation
      run: |
        foamRun -help
        echo "OpenFOAM v12 and OpenMPI installation successful."

    - name: Run Example Simulation
      run: |
        mkdir -p $FOAM_RUN
        cd $FOAM_RUN
        cp -r $FOAM_TUTORIALS/incompressibleFluid/pitzDailySteady .
        cd pitzDailySteady
        blockMesh
        foamRun
        paraFoam
