name: Install OpenFOAM from Repository

on:
  push:
    branches:
      - master
      - main

jobs:
  setup-openfoam:
    name: Setup OpenFOAM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add OpenFOAM Repository and Key
      run: |
        # Add OpenFOAM repository and signing key
        curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash

    - name: Update Package List
      run: |
        # Update package repository information
        sudo apt-get update

    - name: Install OpenFOAM
      run: |
        # Install OpenFOAM (e.g., version openfoam2412-default)
        sudo apt-get install -y openfoam2412-default

    - name: Verify OpenFOAM Installation
      run: |
        # Check the binaries are installed in the expected location
        ls /usr/bin | grep openfoam || echo "OpenFOAM binaries not found!"
        ls /usr/share/openfoam || echo "OpenFOAM configuration directory missing!"

    - name: Configure OpenFOAM Environment
      run: |
        # Manually configure OpenFOAM environment
        echo "export WM_PROJECT_DIR=/usr/share/openfoam" >> ~/.bashrc
        echo "export PATH=/usr/bin:\$PATH" >> ~/.bashrc
        echo "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Test OpenFOAM Session
      run: |
        # Start an OpenFOAM shell session and test the environment
        source ~/.bashrc
        openfoam2412 -help || echo "OpenFOAM command not found!"

    - name: Test OpenFOAM Example
      run: |
        # Run an OpenFOAM example to verify functionality
        mkdir -p $HOME/OpenFOAM/run
        cd $HOME/OpenFOAM/run
        blockMesh -help || echo "blockMesh command not found!"
