name: Fix OpenFOAM Installation

on:
  push:
    branches:
      - master
      - main

jobs:
  fix-openfoam:
    name: Fix OpenFOAM Installation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Enable Universe Repository
      run: |
        sudo apt-add-repository universe
        sudo apt update

    - name: Add OpenFOAM Repository and Public Key
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu

    - name: Update Package List
      run: |
        sudo apt update

    - name: Install OpenFOAM v12
      run: |
        sudo apt -y install openfoam12

    - name: Set OpenMPI as Default
      run: |
        sudo update-alternatives --set mpi /usr/lib/openmpi/include

    - name: Add OpenFOAM to .bashrc
      run: |
        echo ". /opt/openfoam12/etc/bashrc" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Verify Installation
      run: |
        foamRun -help
        echo "OpenFOAM installation fixed."
