name: Run Ubuntu with X11

on: [push]

jobs:
  ubuntu-x11:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: Update and Install Dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          xvfb \
          xauth \
          fluxbox \
          gnome-terminal \
          chromium-browser \
          openfoam \
          python3-pip

    - name: Install Selenium via pip3
      run: |
        pip3 install selenium

    - name: Set up Xvfb
      run: |
        Xvfb :99 -screen 0 1280x1024x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Create .Xauthority
      run: |
        touch ~/.Xauthority
        xauth generate :99 . trusted
        chmod 600 ~/.Xauthority

    - name: Start Fluxbox (Optional - for visual confirmation)
      run: |
        fluxbox &

    - name: Print VNC Connection Instructions
      run: |
        echo "To connect via VNC, follow these steps:"
        echo "1. Start a VNC viewer (e.g., TigerVNC, RealVNC, or TightVNC)."
        echo "2. Enter the correct IP address and port for your container."
        echo "3. Ensure X11 forwarding is correctly set up if using SSH tunneling."
        echo "4. Use your VNC credentials if required."
        echo "Note: GitHub Actions does not expose VNC ports by default. If needed, you'd need an SSH tunnel."

    - name: Wait for 3 minutes before stopping container
      run: |
        echo "Waiting for 3 minutes before stopping the container..."
        sleep 180

    - name: Stop and Remove Container
      run: |
        CONTAINER_ID=$(docker ps -q)
        if [ ! -z "$CONTAINER_ID" ]; then
          echo "Stopping and removing container: $CONTAINER_ID"
          docker rm --force "$CONTAINER_ID"
        fi

    - name: Remove Container Network
      run: |
        NETWORK_ID=$(docker network ls | grep github_network | awk '{print $1}')
        if [ ! -z "$NETWORK_ID" ]; then
          echo "Removing container network: $NETWORK_ID"
          docker network rm "$NETWORK_ID"
        fi
