name: Resolve OpenMPI Conflicts for OpenFOAM

on:
  push:
    branches:
      - master
      - main

jobs:
  configure-openmpi:
    name: Resolve MPI Conflicts and Configure OpenMPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Enable Universe Repository
      run: |
        sudo apt-add-repository universe
        sudo apt update

    - name: Install OpenMPI
      run: |
        sudo apt install -y openmpi-bin libopenmpi-dev

    - name: Remove Existing Conflicting MPI Alternatives
      run: |
        sudo update-alternatives --remove mpi /usr/bin/mpiexec || true
        sudo update-alternatives --remove mpi /usr/bin/mpirun || true
        sudo update-alternatives --remove mpi /usr/bin/mpicc.openmpi || true
        sudo rm /usr/bin/mpiexec || true
        sudo rm /usr/bin/mpirun || true

    - name: Re-register OpenMPI Alternatives
      run: |
        sudo update-alternatives --install /usr/bin/mpicc mpi /usr/bin/mpicc.openmpi 50
        sudo update-alternatives --install /usr/bin/mpiexec mpi /usr/bin/mpiexec.openmpi 50
        sudo update-alternatives --install /usr/bin/mpirun mpi /usr/bin/mpirun.openmpi 50

    - name: Set OpenMPI as Default
      run: |
        sudo update-alternatives --set mpi /usr/bin/mpicc.openmpi

    - name: Verify OpenMPI Configuration
      run: |
        update-alternatives --query mpi
        mpicc --version
        mpiexec --version
