name: Fix OpenMPI for OpenFOAM Installation

on:
  push:
    branches:
      - master
      - main

jobs:
  configure-openmpi:
    name: Configure OpenMPI for OpenFOAM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Enable Universe Repository
      run: |
        sudo apt-add-repository universe
        sudo apt update

    - name: Install OpenMPI
      run: |
        sudo apt install -y openmpi-bin libopenmpi-dev

    - name: Register OpenMPI in Alternatives
      run: |
        sudo update-alternatives --install /usr/bin/mpicc mpi /usr/bin/mpicc.openmpi 50
        sudo update-alternatives --install /usr/bin/mpicxx mpi /usr/bin/mpicxx.openmpi 50
        sudo update-alternatives --install /usr/bin/mpiexec mpi /usr/bin/mpiexec.openmpi 50
        sudo update-alternatives --install /usr/bin/mpirun mpi /usr/bin/mpirun.openmpi 50

    - name: Set OpenMPI as Default
      run: |
        sudo update-alternatives --set mpi /usr/bin/mpicc.openmpi

    - name: Verify OpenMPI Installation
      run: |
        mpicc --version
        mpirun --version
