name: Install OpenFOAM v12

on:
  push:
    branches:
      - master
      - main

jobs:
  install-openfoam:
    name: Install OpenFOAM v12
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add OpenFOAM Repository and Public Key
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu

    - name: Update Package List
      run: |
        sudo apt update

    - name: Install OpenFOAM v12
      run: |
        sudo apt -y install openfoam12

    - name: Add OpenFOAM to .bashrc
      run: |
        echo ". /opt/openfoam12/etc/bashrc" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Verify Installation
      run: |
        foamRun -help
        echo "OpenFOAM v12 installation successful."
